### PR TITLE
test(bin-utils): adjusted paths separator

### PR DESCRIPTION
**Pull request by Miklet**
Adjusted paths to match linux format on windows os.

**What**: Fixed tests for bin-utils on Windows

**Why**: Tests were failing on Windows

**How**: Adjusted paths seperator

### CODE REVIEW

**Comment by Miklet** [comment]
Sorry for that merge, I made a branch from old code without my old changes. If you want to keep a clean git history you can decline this pull request and I will make another one.

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the CONTRIBUTING.md file (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by Miklet** [comment]
Wow, I feel honored! Will try to do my best and to not disappoint you.

**Comment by kentcdodds** [comment]
You're already doing awesome man. Thanks for all your hard work :D

**Comment by Miklet** [comment]
You're welcome! This project is really nice and I enjoy working on it :-)

**Pull request merged**
