### PR TITLE
feat(init): keep pre and post scripts as they work in npm

### PR DESCRIPTION
**Pull request by Miklet**
**What**: I've added proper handling of pre and post scripts.

**Why**: To make nps scripts work same as how they work in npm.

**How**: Modified method responsible for structuring scripts before they are serialized to string. Also adjusted tests.

Could you look for expected yaml file? I am not familiar with this type of file and want to be sure I edited it correctly. Using quotes in this format of file is really confusing 😖 

https://github.com/kentcdodds/nps/issues/108

### CODE REVIEW

**Comment by Miklet** [comment]
@kentcdodds Shall I accept my own pull request or could you look at it :)?

**Comment by kentcdodds** [comment]
Give me a little more time to review it please 😀

**Comment by Miklet** [comment]
Yea, sure. I was just asking, there is no hurry :-)

**Comment by kentcdodds** [comment]
Thanks a bunch for doing this!

**Comment by Miklet** [comment]
You're welcome as always 😄

**Pull request merged**
