### PR TITLE
test(cli): fixed tests under windows

### PR DESCRIPTION
**Pull request by Miklet**
I've fixed tests for cli under windows os. Problems with tests were caused because of platform
diffreneces between windows and linux i.e. paths separator, output from echo command.

https://github.com/kentcdodds/nps/issues/129

**What**: I've changed tests for cli to run them successfully under windows.

**Why**: Because people like I, who use windows, couldn't setup project locally properly because of tests failing on our operating system.

**How**: I have tweaked one method and added a new one which removes unnecessary quotes from stdout result in tests output.

P.S. forgive me my lack of knowledge about contributing, it is my first time.

### CODE REVIEW

**Comment by Miklet** [comment]
I ran commands and there are no changes :) I've just adjusted tests too be more versatile and still match actual output without changing it.

**Comment by kentcdodds** [comment]
Oh, awesome! Thank you again!

**Comment by kentcdodds** [comment]
Congrats on your first pull request! Thank you for your contribution!

**Comment by Miklet** [comment]
Thank you very much, I feel great that I could help. I saw that there are still some issues to be done, will look at them to help a little more.

**Comment by kentcdodds** [comment]
Terrific!

**Pull request merged**
